name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v22.2
      - name: Run a multi-line script
        run: |
          git config --global user.email "sahmad@kloudrac.com"
          git config --global user.name "samirkloudrac"
      - name: List all changed files
        run: |
          git clone https://samirkloudrac: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@github.com/samirkloudrac/SFDevOps
          cd SFDevOps
          git checkout development
          mkdir -p deployment
          cp "manifest/package.xml" "deployment/"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
             cp "$file" "deployment/"
             cp "$file-meta.xml" "deployment/"   
          done
          git add .
          git commit -m "Committed from Github Actions" deployment
          git push origin HEAD:master
